### ISSUE TITLE
[FEATURE] Dev: Footer Component

### ISSUE THREAD

**Issue by thelegendofkayla** [womencodersnet/wcn-website#4]
Design and implement a footer component for the W.E. Tech website's MVP. The footer should be visually appealing and user-friendly.

Acceptance Criteria (AC):
Ensure the footer is responsive and functions well on desktop and mobile devices.
(email for inquiries and social media links (#25) will be separate tasks)

Note: as of 4/30, there is a footer template generated for customization in the app/components/footer.tsx file.

**Comment by amelia2802** [comment]
# Actions Taken:

- Following the [Figma design](https://www.figma.com/design/pGmEzUs7fupEhQ22nii4fV/v1?node-id=0-1&t=7NEKjkqrlrvo8f5Y-1), I've created the footer component with respective brand colors and icons
- In the same branch, added the brand-colored favicon and added it as a sub-issue with the footer
- Remodified the `enhancement` issue template to `task` as suggested by @sunsplat 

# Preview
| Footer   | Favicon | Issue Template |
| -------- | ------- | ------- |
| ![Image](https://github.com/user-attachments/assets/50cc4dc6-e92c-4c2f-b1f1-31190ccf2cdf) | ![Image](https://github.com/user-attachments/assets/ba5ba825-1ee5-4a98-8cfc-0fdf8f4431c7) | ![Image](https://github.com/user-attachments/assets/83ca4437-72db-4482-83b5-305760f5ba3e) |

# TODO
- [ ] Design the hover effect for the `Code of Conduct` button
- [ ] Set the font `Roboto mono` in the global.css, as for now without explicitly mentioning the font is set to `Inter`
- [ ] Need the footer design for mobile/tablet view

**Current Design**
![Image](https://github.com/user-attachments/assets/27ac770e-6841-4fdc-8cb7-db6153b743e3)


@sunsplat , @hernandezforges here are my updates. I'd like to hear your thoughts.

**Comment by hernandezforges** [comment]
@amelia2802 Nice work! It looks really good, exactly like the design! 💚 

@sunsplat Do you think we should put this and any other mobile related issues on hold until we can put together a mobile specific design? Or we can try tackling/talking through some of the pain points at our next meeting and then decide from there? 

Personally, I won't have much time to go over or create a design, since I have work scheduled the next two weeks/weekends.

**Comment by hernandezforges** [comment]
Another separate, but related, thought is that we should update the design to better match the color palette of our logo. I'm currently talking with someone about creating a Figma color system for us, so once I hear back from them I can create and tackle that issue.

**Comment by sunsplat** [comment]
@amelia2802 @hernandezforges TailwindCSS should automatically have the [mobile responsiveness](https://tailwindcss.com/docs/responsive-design) capability. I think as part of this story we can just make sure the footer still shows up and isn't broken on smaller devices. We can improve the design for mobile using Figma and create new issues to update to that design. What do you think?

Also, Amelia, please complete the tasks in our project on their own separate branches. Create separate branches for the work, so that we can merge changes into our website faster and it's easer to review. 

This https://github.com/womencodersnet/wcn-website/issues/39 isn't really a sub-issue of a footer as it applies to the whole website and should be it's standalone task.

For example, because the favicon changes are now on the footer branch, we can't see those changes until the footer is done, so now you've created unnecessary dependencies. Same with including the update for the issue template. This task and your branch should all be strictly footer related. Separating out the concerns will be a good practice!

This task can be part of UX: Fonts issue: 
- Set the font Roboto mono in the global.css, as for now without explicitly mentioning the font is set to Inter

Is this the font we are all deciding? Or are you just updating to it for fun?

**Comment by amelia2802** [comment]
@sunsplat , Thanks for the feedback and I'll create separe brancehes for those pr

I believe `Roboto mono` is the font used in the Figma design.

**Comment by amelia2802** [comment]
I think a separate issue for the screen-based layout will be good because for desktop/large screens the footer elements align horizontally, which may or may not look good on small screens. Also the font size may differ.

**Comment by hernandezforges** [comment]
@sunsplat, Thanks for the explanations. The issues were my fault, I'll keep your advice in mindmoving forward. Also, I don't think the team or community ever decided on any typography, so I'm fine with whatever. At least until I can get a designer to join us. 

I've made a new section in our [meeting notes](https://docs.google.com/document/d/1aHrJYVbv3DdjtajKyeNW-pMreyvAVSW9WmfFhoRGZqo/edit?usp=sharing) for Design Tasks. Just so I can remember everything we need or has been brought up and everyone on the team is aware.
